# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

target 'SSPagerExample' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SSPagerExample
  pod 'SSPager/Rx', '~> 1.0.0'

end
